builddrafts = false
baseurl = "http://modernfidelity.github.io/"
languageCode = "en-uk"
title = "Mofi Blog"
theme = "mofi1"

preserveTaxonomyNames = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Tech blog made of awesome"
  author = "Mark Rushton"